### ISSUE TITLE
passwordless URL support in string representation

### ISSUE THREAD

**Issue by mieciu** [codeinthehole/purl#19]
Hi, 

Today I've discovered quite weird behaviour - please have a look at snippet below:
```
>>> from purl import URL
>>> url = URL(scheme='postgres', username='user', host='127.0.0.1', port='5432', path='/db_name')
>>> url.as_string()
u'postgres://127.0.0.1:5432/db_name'        # Username disappeared 
>>> url = URL(scheme='postgres', username='user', password='pass', host='127.0.0.1', port='5432', path='/db_name')
>>> url.as_string()
u'postgres://user:pass@127.0.0.1:5432/db_name'        # In combination w/ passord it works
```
Of course its being stored properly:
```
>>> url = URL(scheme='postgres', username='user', host='127.0.0.1', port='5432', path='/db_name')
>>> url
_URLTuple(host='127.0.0.1', username='user', password=None, scheme='postgres', port='5432', path='/db_name', query=None, fragment=N
one)
>>> url.username
<bound method URL.username of _URLTuple(host='127.0.0.1', username='user', password=None, scheme='postgres', port='5432', path='/db
_name', query=None, fragment=None)>
>>> url.username()
u'user'
```

I think that passwordless URLs should be supported, as - for instance - following postgres URL is fully proper: `psql "postgres://postgres@192.168.99.100:5432/template1"`

It should be relatively easy to fix, I'll try to submit a patch this week, but what do you think about this?

**Comment by mieciu** [comment]
This is even more worrying:
```
>>> url = URL.from_string('postgres://user@127.0.0.1:5432/db_name')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "purl/url.py", line 505, in from_string
    This method is deprecated now
  File "purl/url.py", line 145, in __init__
    params = parse(url_str)
  File "purl/url.py", line 106, in parse
    username, password = netloc_parts[0].split(':')
ValueError: need more than 1 value to unpack
```

I'll submit a patch tomorrow morning :)

**Comment by mieciu** [comment]
My solution comes with PR #20
