### ISSUE TITLE
Cannot be installed using buildout

### ISSUE THREAD

**Issue by href** [codeinthehole/purl#25]
When I try to install purl 1.2 using buildout I get the following error:

```python
Traceback (most recent call last):
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 154, in save_modules
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 195, in setup_context
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 239, in run_setup
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 269, in run
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 238, in runner
  File "/Users/denis/.buildout/eggs/setuptools-19.4-py3.5.egg/setuptools/sandbox.py", line 46, in _execfile
  File "/var/folders/mm/5rlp4h9906n3npgjt96lm0fw0000gn/T/easy_install-4zdguc7q/purl-1.2/setup.py", line 5, in <module>
  File "/var/folders/mm/5rlp4h9906n3npgjt96lm0fw0000gn/T/easy_install-4zdguc7q/purl-1.2/purl/__init__.py", line 1, in <module>
  File "/var/folders/mm/5rlp4h9906n3npgjt96lm0fw0000gn/T/easy_install-4zdguc7q/purl-1.2/purl/url.py", line 10, in <module>
ImportError: No module named 'six'
```

The problem seems to be that you try to import the package in `setup.py`, when it's not yet installed. This works if six is installed, or indeed if pip is used (because pip has a workaround for this). What you should be doing is either define the version twice in the `__init__.py` as well as `setup.py`. Or you open `__init__.py` as text and parse the version statically.

**Comment by specialunderwear** [comment]
Also can not be installed with pip:

```
Downloading/unpacking purl>=0.7 (from django-oscar)
  Downloading purl-1.2.tar.gz
  Running setup.py egg_info for package purl
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/ebone/.virtualenvs/kutzooi/build/purl/setup.py", line 5, in <module>
        from purl import __version__
      File "purl/__init__.py", line 1, in <module>
        from .url import URL  # noqa
      File "purl/url.py", line 10, in <module>
        import six
    ImportError: No module named six
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/ebone/.virtualenvs/kutzooi/build/purl/setup.py", line 5, in <module>

    from purl import __version__

  File "purl/__init__.py", line 1, in <module>

    from .url import URL  # noqa

  File "purl/url.py", line 10, in <module>

    import six

ImportError: No module named six
```

Seems you are referencing your main module in setup.py through __init__

**Comment by specialunderwear** [comment]
You can only install this package if all purl's dependencies are in your python path on the moment of installation

**Comment by specialunderwear** [comment]
You will not have this problems if you allow pip to install wheels, since a wheel only uses setup.py during the creation of the wheel.
